# Generated by Django 5.0.1 on 2024-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="savings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
