# Generated by Django 5.0.1 on 2024-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_profile_savings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currency_money",
            field=models.CharField(default="RON", max_length=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="currency_savings",
            field=models.CharField(default="RON", max_length=3),
        ),
        migrations.AlterField(
            model_name="card",
            name="currency",
            field=models.CharField(default="RON", max_length=3),
        ),
        migrations.AlterField(
            model_name="limit",
            name="currency",
            field=models.CharField(default="RON", max_length=3),
        ),
        migrations.DeleteModel(
            name="SavingsPlan",
        ),
    ]
